run:
  modules-download-mode: readonly
  tests: false
  skip-dirs:
    - .vendor

linters:
  enable-all: true
  disable:
    - goconst
    - gochecknoglobals

linters-settings:
  gocritic:
    disabled-checks:
      - ifElseChain

