before:
  hooks:
    - go mod download

builds:
  - main: ./cmd/vcsinfo.go
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goos:
      - linux
      - darwin
      - freebsd
      - openbsd
      - netbsd
    ignore:
      - goos: darwin
        goarch: 386

archives:
  - replacements:
      darwin: macos

changelog:
  skip: true

nfpms:
  - homepage: https://github.com/jayclassless/vcsinfo
    maintainer: "Jason Simeone <jay@classless.net>"
    description: A tool for retrieving/displaying basic information about the status of a VCS repository.
    license: MIT
    formats:
      - deb
      - rpm
    recommends:
      - bzr
      - cvs
      - git
      - fossil
      - darcs
      - svn
      - mercurial

brews:
  - github:
      owner: jayclassless
      name: homebrew-vcsinfo
    folder: Formula
    homepage: https://github.com/jayclassless/vcsinfo
    description: A tool for retrieving/displaying basic information about the status of a VCS repository.

