language: go

go:
  - "1.11.x"

env:
  - GO111MODULE=on

install:
  - make init
  - go get github.com/mattn/goveralls
  - apt-get install fossil cvs darcs

script:
  - make test
  - $GOPATH/bin/goveralls -service=travis-ci -coverprofile=coverage.out

