on: push

name: Run Tests

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1

      - name: Run test suite
        uses: ./.github/actions/testenv
        env:
          COVERALLS_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
        with:
          args: make ci-gha

