on:
  push:
    tags:
      - '*'

name: Publish Release

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1

      - name: Run GoReleaser
        uses: docker://goreleaser/goreleaser:v0.117.2
        env:
          GITHUB_TOKEN: ${{ secrets.GORELEASER_GITHUB_TOKEN }}
        with:
          args: release
        if: success()

